= Build & Deployment Considerations
== Workspace Targets
RegViz ships as a Cargo workspace with `regviz_app` marked as the default package. This means a bare `cargo build` compiles the frontend together with its dependency on `regviz_core`, while `cargo run` launches the native desktop client using Iced's renderer.

#figure(
  ```bash
  # Native debugging session
  cargo run

  # When iterating on the backend crate alone
  cargo test --package regviz_core

  # CLI helper (prints AST/NFA/DFA stats and optional acceptance results)
  cargo run --package regviz_core -- "(a+b)*c" "abbc"
  ```,
  caption: [Core workspace commands (`Cargo.toml` workspace root)],
) <fig:build-cli>

The backend and frontend share the same language runtime, so there is no foreign-function glue code: the GUI simply `use`s `regviz_core::{core::dfa, core::nfa, ...}` directly.

== WebAssembly Preview
The repository also includes a WASM build driven by Trunk (`Trunk.toml`). After adding the `wasm32-unknown-unknown` target and installing Trunk, `trunk serve --open` recompiles the app with the `wasm-bindgen` shims that Iced expects in the browser. Fonts are embedded via the `embed-fonts` feature flag so the UI matches the desktop build without system dependencies.

#figure(
  ```bash
  rustup target add wasm32-unknown-unknown
  cargo install trunk
  cd crates/regviz_app
  trunk serve --open
  ```,
  caption: [Launching the WASM preview (`crates/regviz_app/Trunk.toml`)],
) <fig:build-trunk>

== Continuous Deployment
Distribution is automated through a GitHub Actions workflow (`.github/workflows/deploy-pages.yml`). When a release is published (or the workflow is manually dispatched), CI performs the following steps:

1. Installs the stable toolchain plus the `wasm32-unknown-unknown` target.
2. Runs `trunk build --release --public-url "/<repo>/"` inside `regviz_app/`.
3. Uploads the resulting `dist/` directory as a Pages artifact and deploys it via `deploy-pages`.

Because all assets are static, GitHub Pages can host the visualization without a backend server. Native binaries remain available for download via the release artifacts generated by `cargo build --release -p regviz_app`, giving instructors multiple delivery options with a shared codebase.
